name: Alumini Job Refer App - AI Assisted

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Ngrok and authenticate
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3.2.0-linux-amd64.zip
        unzip ngrok-v3.2.0-linux-amd64.zip
        ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        ./ngrok http --domain=smart-insect-cleanly.ngrok-free.app 8000 &

    - name: Run Uvicorn app
      run: |
        uvicorn routes:app --host 0.0.0.0 --port 8000 
        echo "Uvicorn app is running at $ngrok_url"
