name: Deploy Uvicorn App

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup ngrok
      run: |
        sudo apt-get update
        sudo apt-get install -y ngrok
        ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Run Uvicorn app
      run: |
        uvicorn routes:app --host 0.0.0.0 --port 8000 &
        ngrok http 8000

    - name: Get ngrok URL
      run: |
        echo "Uvicorn app is running at $(ngrok url)"
